root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main"
cmd = "TEMPL_EXPERIMENT=rawgo templ generate && npx tailwindcss -c ./frontend/tailwind.config.js -i ./frontend/src/index.css -o ./frontend/public/index.css && npm --prefix ./frontend run  build && go build -o ./tmp/main ./cmd/command/"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "node_modules"]
exclude_file = [
    'frontend/package-lock.json',
    'frontend/package.json',
    'frontend/dist/index.js',
    'frontend/dist/index.css',
]
exclude_regex = [".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html", "js"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false

[proxy]
enabled = true
proxy_port = 8080
app_port = 8000
